/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.velikiyprikalel.api;

import com.velikiyprikalel.model.SystemItem;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@Validated
@RequestMapping("${openapi.yetAnotherDiskOpen.base-path:}")
public interface NodesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /nodes/{id}
     * Получить информацию об элементе по идентификатору. При получении информации о
     * папке также предоставляется информация о её дочерних элементах. - для пустой
     * папки поле children равно пустому массиву, а для файла равно null - размер
     * папки - это суммарный размер всех её элементов. Если папка не содержит
     * элементов, то размер равен 0. При обновлении размера элемента, суммарный
     * размер папки, которая содержит этот элемент, тоже обновляется.
     *
     * @param id Идентификатор элемента (required)
     * @return Информация об элементе. (status code 200)
     *         or Невалидная схема документа или входные данные не верны. (status
     *         code 400)
     *         or Элемент не найден. (status code 404)
     */
    @RequestMapping(method = RequestMethod.GET, value = "/nodes/{id}", produces = { "application/json" })
    default ResponseEntity<SystemItem> nodesIdGet(
            @PathVariable("id") String id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
